[package]
name = "net"
version = "0.1.0"
edition = "2024"

[dependencies]
common = {path = "../../crates/common"}
tokio = {version = "1.48.0", features = ["full"]}
tokio-util = { version = "0.7.16", features = ["codec"] }
futures = "0.3.31"
tracing = "0.1.41"
anyhow = "1.0.100"
bytes = "1.10.1"
