// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DirectMessage {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub timestamp: u64,
    #[prost(oneof = "direct_message::Payload", tags = "10, 11, 12, 13")]
    pub payload: ::core::option::Option<direct_message::Payload>,
}
/// Nested message and enum types in `DirectMessage`.
pub mod direct_message {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "10")]
        Text(super::Text),
        #[prost(message, tag = "11")]
        Delivered(super::Delivered),
        #[prost(message, tag = "12")]
        Read(super::Read),
        #[prost(message, tag = "13")]
        Typing(super::Typing),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Text {
    /// encrypted payload
    #[prost(bytes = "vec", tag = "1")]
    pub content: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Delivered {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Read {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Typing {
    #[prost(bool, tag = "1")]
    pub is_typing: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DirectMessageResponse {
    #[prost(oneof = "direct_message_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<direct_message_response::Result>,
}
/// Nested message and enum types in `DirectMessageResponse`.
pub mod direct_message_response {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Ack(super::Ack),
        #[prost(message, tag = "2")]
        Error(super::Error),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Ack {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Error {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
