// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GroupMessage {
    #[prost(string, tag = "1")]
    pub group_id: ::prost::alloc::string::String,
    /// PeerId
    #[prost(string, tag = "2")]
    pub sender: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub timestamp: u64,
    /// critical for dedup / ordering
    #[prost(uint64, tag = "5")]
    pub seq_no: u64,
    /// encrypted group payload
    #[prost(bytes = "vec", tag = "6")]
    pub content: ::prost::alloc::vec::Vec<u8>,
}
